# Generated by Django 2.2.4 on 2019-08-11 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blogger',
            new_name='commenter',
        ),
    ]
