# Generated by Django 2.2.4 on 2019-08-11 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190811_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='corresp_post',
            new_name='corresponding_post',
        ),
    ]
