# Generated by Django 2.2.4 on 2019-08-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190812_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='bio',
            field=models.TextField(default="This user doesn't have a bio, he/she is a blank person.", help_text='Some words about yourself...', max_length=200),
        ),
    ]
