# Generated by Django 2.2.4 on 2019-08-14 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogger_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='user_name',
        ),
    ]
