# Generated by Django 2.2.4 on 2019-08-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190813_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='bio',
            field=models.TextField(default="This user doesn't have a bio, he/she is a blank person.", help_text='Some words about yourself...', max_length=200),
        ),
        migrations.AddField(
            model_name='blogger',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='blogger',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='blogger',
            name='user_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
