# Generated by Django 2.2.4 on 2019-08-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190813_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='bio',
            field=models.TextField(default="This user doesn't have a bioblank person.", help_text='Some words about yourself...', max_length=200),
        ),
    ]
