# Generated by Django 2.2.4 on 2019-08-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190825_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='bio',
            field=models.TextField(default='Insert Bio Here...', help_text='Some words about yourself...'),
        ),
    ]
